title: Baker Street Forensics
description: Where Irregulars are Part of the Game
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme